
const displayConfig = (function() {
    const displayGroups = [

		// ======================================== PixelPhase1 ========================================
		{
			name: "HitEfficiency_BPix_perLayer_group",
			plot_title: "BPIX  Hit Efficiency per layer",
			y_title: "BPIX  Hit Efficiency per layer",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["HitEfficiency_BPix_perLayer", "HitEfficiency_BPix_Layer2", "HitEfficiency_BPix_Layer3", "HitEfficiency_BPix_Layer4"],
		},
		{
			name: "HitEfficiency_FPix_perDisk_group",
			plot_title: "FPIX  Hit Efficiency per disk",
			y_title: "FPIX  Hit Efficiency per disk",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["HitEfficiency_FPix_perDisk", "HitEfficiency_FPix_Dm2", "HitEfficiency_FPix_Dm1", "HitEfficiency_FPix_Dp3", "HitEfficiency_FPix_Dp2", "HitEfficiency_FPix_Dp1"],
		},
		{
			name: "clustCharge_ONTk_FPix_perDisk_mpv_group",
			plot_title: "FPIX Cluster Charge OnTrack per disk (mpv)",
			y_title: "FPIX Cluster Charge OnTrack per disk (mpv)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["clustCharge_ONTk_FPix_perDisk_mpv", "clustCharge_ONTk_FPix_Dm2_mpv", "clustCharge_ONTk_FPix_Dm1_mpv", "clustCharge_ONTk_FPix_Dp3_mpv", "clustCharge_ONTk_FPix_Dp2_mpv", "clustCharge_ONTk_FPix_Dp1_mpv"],
		},
		{
			name: "size_ONTk_FPix_perDisk_mean_group",
			plot_title: "FPIX average cluster size OnTrack per disk (in pixels)",
			y_title: "FPIX average cluster size OnTrack per disk (in pixels)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["size_ONTk_FPix_perDisk_mean", "size_ONTk_FPix_Dm2_mean", "size_ONTk_FPix_Dm1_mean", "size_ONTk_FPix_Dp3_mean", "size_ONTk_FPix_Dp2_mean", "size_ONTk_FPix_Dp1_mean"],
		},
		{
			name: "adc_FPix_perDisk_mean_group",
			plot_title: "FPIX Digi ADC per disk (mean value)",
			y_title: "FPIX Digi ADC per disk (mean value)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["adc_FPix_perDisk_mean", "adc_FPix_Dm2_mean", "adc_FPix_Dm1_mean", "adc_FPix_Dp3_mean", "adc_FPix_Dp2_mean", "adc_FPix_Dp1_mean"],
		},
		{
			name: "clustCharge_ONTk_BPix_perLayer_mpv_group",
			plot_title: "BPIX Cluster Charge OnTrack per layer (mpv)",
			y_title: "BPIX Cluster Charge OnTrack per layer (mpv)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["clustCharge_ONTk_BPix_perLayer_mpv", "clustCharge_ONTk_BPix_Layer2_mpv", "clustCharge_ONTk_BPix_Layer3_mpv", "clustCharge_ONTk_BPix_Layer4_mpv"],
		},
		{
			name: "size_ONTk_BPix_perLayer_mean_group",
			plot_title: "BPIX average cluster size OnTrack per layer (in pixels)",
			y_title: "BPIX average cluster size OnTrack per layer (in pixels)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["size_ONTk_BPix_perLayer_mean", "size_ONTk_BPix_Layer2_mean", "size_ONTk_BPix_Layer3_mean", "size_ONTk_BPix_Layer4_mean"],
		},
		{
			name: "adc_BPix_perLayer_mean_group",
			plot_title: "BPIX Digi ADC per layer (mean value)",
			y_title: "BPIX Digi ADC per layer (mean value)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["adc_BPix_perLayer_mean", "adc_BPix_Layer2_mean", "adc_BPix_Layer3_mean", "adc_BPix_Layer4_mean"],
		},
		{
			name: "clustCharge_ONTk_BPix_perInOutLayer_mpv_group",
			plot_title: "BPIX Cluster Charge OnTrack per inner/outer layer (mpv)",
			y_title: "BPIX Cluster Charge OnTrack per inner/outer layer (mpv)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["clustCharge_ONTk_BPix_perInOutLayer_mpv", "clustCharge_ONTk_BPix_OuterLayer1_mpv", "clustCharge_ONTk_BPix_InnerLayer2_mpv", "clustCharge_ONTk_BPix_OuterLayer2_mpv", "clustCharge_ONTk_BPix_InnerLayer3_mpv", "clustCharge_ONTk_BPix_OuterLayer3_mpv", "clustCharge_ONTk_BPix_InnerLayer4_mpv", "clustCharge_ONTk_BPix_OuterLayer4_mpv"],
		},
		{
			name: "DigiPerClusterPixel_BPix_perLayer_group",
			plot_title: "BPIX total number of digis over digis in clusters per layer",
			y_title: "BPIX total number of digis over digis in clusters per layer",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["DigiPerClusterPixel_BPix_perLayer", "DigiPerClusterPixel_BPix_Layer2", "DigiPerClusterPixel_BPix_Layer3", "DigiPerClusterPixel_BPix_Layer4"],
		},
		{
			name: "DigiPerClusterPixel_FPix_perDisk_group",
			plot_title: "FPIX total number of digis over digis in clusters",
			y_title: "FPIX total number of digis over digis in clusters",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["DigiPerClusterPixel_FPix_perDisk", "DigiPerClusterPixel_FPix_Dm2", "DigiPerClusterPixel_FPix_Dm1", "DigiPerClusterPixel_FPix_Dp3", "DigiPerClusterPixel_FPix_Dp2", "DigiPerClusterPixel_FPix_Dp1"],
		},
		{
			name: "Residuals_X_BPIX_perLayer_mean_group",
			plot_title: "Residuals X BPIX per layer (Mean)",
			y_title: "Residuals X BPIX per layer (Mean)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["Residuals_X_BPIX_perLayer_mean", "Residuals_X_BPIX_L2_mean", "Residuals_X_BPIX_L3_mean", "Residuals_X_BPIX_L4_mean"],
		},
		{
			name: "Residuals_X_BPIX_perLayer_rms_group",
			plot_title: "Residuals X BPIX per layer (RMS)",
			y_title: "Residuals X BPIX per layer (RMS)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["Residuals_X_BPIX_perLayer_rms", "Residuals_X_BPIX_L2_rms", "Residuals_X_BPIX_L3_rms", "Residuals_X_BPIX_L4_rms"],
		},
		{
			name: "Residuals_Y_BPIX_perLayer_mean_group",
			plot_title: "Residuals Y BPIX per layer (Mean)",
			y_title: "Residuals Y BPIX per layer (Mean)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["Residuals_Y_BPIX_perLayer_mean", "Residuals_Y_BPIX_L2_mean", "Residuals_Y_BPIX_L3_mean", "Residuals_Y_BPIX_L4_mean"],
		},
		{
			name: "Residuals_Y_BPIX_perLayer_rms_group",
			plot_title: "Residuals Y BPIX per layer (RMS)",
			y_title: "Residuals Y BPIX per layer (RMS)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["Residuals_Y_BPIX_perLayer_rms", "Residuals_Y_BPIX_L2_rms", "Residuals_Y_BPIX_L3_rms", "Residuals_Y_BPIX_L4_rms"],
		},
		{
			name: "Residuals_X_FPIX_perMinusDisk_mean_group",
			plot_title: "Residuals X FPIX per disk - (Mean)",
			y_title: "Residuals X FPIX per disk - (Mean)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["Residuals_X_FPIX_perMinusDisk_mean", "Residuals_X_FPIX_Dm2_mean", "Residuals_X_FPIX_Dm1_mean"],
		},
		{
			name: "Residuals_X_FPIX_perMinusDisk_rms_group",
			plot_title: "Residuals X FPIX per disk - (RMS)",
			y_title: "Residuals X FPIX per disk - (RMS)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["Residuals_X_FPIX_perMinusDisk_rms", "Residuals_X_FPIX_Dm2_rms", "Residuals_X_FPIX_Dm1_rms"],
		},
		{
			name: "Residuals_Y_FPIX_perMinusDisk_mean_group",
			plot_title: "Residuals Y FPIX per disk - (Mean)",
			y_title: "Residuals Y FPIX per disk - (Mean)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["Residuals_Y_FPIX_perMinusDisk_mean", "Residuals_Y_FPIX_Dm2_mean", "Residuals_Y_FPIX_Dm1_mean"],
		},
		{
			name: "Residuals_Y_FPIX_perMinusDisk_rms_group",
			plot_title: "Residuals Y FPIX per disk - (RMS)",
			y_title: "Residuals Y FPIX per disk - (RMS)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["Residuals_Y_FPIX_perMinusDisk_rms", "Residuals_Y_FPIX_Dm2_rms", "Residuals_Y_FPIX_Dm1_rms"],
		},
		{
			name: "Residuals_X_FPIX_perPlusDisk_mean_group",
			plot_title: "Residuals X FPIX per disk + (Mean)",
			y_title: "Residuals X FPIX per disk + (Mean)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["Residuals_X_FPIX_perPlusDisk_mean", "Residuals_X_FPIX_Dp2_mean", "Residuals_X_FPIX_Dp1_mean"],
		},
		{
			name: "Residuals_X_FPIX_perPlusDisk_rms_group",
			plot_title: "Residuals X FPIX per disk + (RMS)",
			y_title: "Residuals X FPIX per disk + (RMS)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["Residuals_X_FPIX_perPlusDisk_rms", "Residuals_X_FPIX_Dp2_rms", "Residuals_X_FPIX_Dp1_rms"],
		},
		{
			name: "Residuals_Y_FPIX_perPlusDisk_mean_group",
			plot_title: "Residuals Y FPIX per disk + (Mean)",
			y_title: "Residuals Y FPIX per disk + (Mean)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["Residuals_Y_FPIX_perPlusDisk_mean", "Residuals_Y_FPIX_Dp2_mean", "Residuals_Y_FPIX_Dp1_mean"],
		},
		{
			name: "Residuals_Y_FPIX_perPlusDisk_rms_group",
			plot_title: "Residuals Y FPIX per disk + (RMS)",
			y_title: "Residuals Y FPIX per disk + (RMS)",
			subsystem: "PixelPhase1",
			correlation: false,
			series: ["Residuals_Y_FPIX_perPlusDisk_rms", "Residuals_Y_FPIX_Dp2_rms", "Residuals_Y_FPIX_Dp1_rms"],
		},

		// ======================================== Pixel ========================================
		{
			name: "HitResiduals_X_FPIX_Dm1_mean_group",
			plot_title: "HitResiduals X FPIX Mean",
			y_title: "HitResiduals X FPIX Mean",
			subsystem: "Pixel",
			correlation: false,
			series: ["HitResiduals_X_FPIX_Dm1_mean", "HitResiduals_X_FPIX_Dp1_mean"],
		},
		{
			name: "HitResiduals_X_FPIX_Dm1_rms_group",
			plot_title: "HitResiduals X FPIX RMS",
			y_title: "HitResiduals X FPIX RMS",
			subsystem: "Pixel",
			correlation: false,
			series: ["HitResiduals_X_FPIX_Dm1_rms", "HitResiduals_X_FPIX_Dp1_rms"],
		},
		{
			name: "HitResiduals_Y_FPIX_Dm1_mean_group",
			plot_title: "HitResiduals Y FPIX Mean",
			y_title: "HitResiduals Y FPIX Mean",
			subsystem: "Pixel",
			correlation: false,
			series: ["HitResiduals_Y_FPIX_Dm1_mean", "HitResiduals_Y_FPIX_Dp1_mean"],
		},
		{
			name: "HitResiduals_Y_FPIX_Dm1_rms_group",
			plot_title: "HitResiduals Y FPIX RMS",
			y_title: "HitResiduals Y FPIX RMS",
			subsystem: "Pixel",
			correlation: false,
			series: ["HitResiduals_Y_FPIX_Dm1_rms", "HitResiduals_Y_FPIX_Dp1_rms"],
		},
		{
			name: "HitResiduals_X_FPIX_Dm2_mean_group",
			plot_title: "HitResiduals X FPIX Mean",
			y_title: "HitResiduals X FPIX Mean",
			subsystem: "Pixel",
			correlation: false,
			series: ["HitResiduals_X_FPIX_Dm2_mean", "HitResiduals_X_FPIX_Dp2_mean"],
		},
		{
			name: "HitResiduals_X_FPIX_Dm2_rms_group",
			plot_title: "HitResiduals X FPIX RMS",
			y_title: "HitResiduals X FPIX RMS",
			subsystem: "Pixel",
			correlation: false,
			series: ["HitResiduals_X_FPIX_Dm2_rms", "HitResiduals_X_FPIX_Dp2_rms"],
		},
		{
			name: "HitResiduals_Y_FPIX_Dm2_mean_group",
			plot_title: "HitResiduals Y FPIX Mean",
			y_title: "HitResiduals Y FPIX Mean",
			subsystem: "Pixel",
			correlation: false,
			series: ["HitResiduals_Y_FPIX_Dm2_mean", "HitResiduals_Y_FPIX_Dp2_mean"],
		},
		{
			name: "HitResiduals_Y_FPIX_Dm2_rms_group",
			plot_title: "HitResiduals Y FPIX RMS",
			y_title: "HitResiduals Y FPIX RMS",
			subsystem: "Pixel",
			correlation: false,
			series: ["HitResiduals_Y_FPIX_Dm2_rms", "HitResiduals_Y_FPIX_Dp2_rms"],
		},

		// ======================================== SiStrips ========================================
		{
			name: "clusterStoN_ONTk_TIB_L1_mpv_group",
			plot_title: "S/N (mpv)",
			y_title: "S/N (mpv)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TIB_L1_mpv", "clusterStoN_ONTk_TIB_L2_mpv", "clusterStoN_ONTk_TIB_L3_mpv", "clusterStoN_ONTk_TIB_L4_mpv"],
		},
		{
			name: "summary_ccpercmfromtrack__tecm_mpv_group",
			plot_title: "cluster charge	per cm (from track)",
			y_title: "cluster charge	per cm (from track)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["summary_ccpercmfromtrack__tecm_mpv", "summary_ccpercmfromtrack__tecp_mpv"],
		},
		{
			name: "summary_ccpercmfromtrack__tidm_mpv_group",
			plot_title: "cluster charge	per cm (from track)",
			y_title: "cluster charge	per cm (from track)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["summary_ccpercmfromtrack__tidm_mpv", "summary_ccpercmfromtrack__tidp_mpv"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel1_mean_group",
			plot_title: "HitResiduals TEC Wheel 1 Mean",
			y_title: "HitResiduals TEC Wheel 1 Mean",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel1_mean", "HitResiduals_TEC_PLUS_wheel1_mean"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel1_rms_group",
			plot_title: "HitResiduals TEC Wheel 1 RMS",
			y_title: "HitResiduals TEC Wheel 1 RMS",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel1_rms", "HitResiduals_TEC_PLUS_wheel1_rms"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel2_mean_group",
			plot_title: "HitResiduals TEC Wheel 2 Mean",
			y_title: "HitResiduals TEC Wheel 2 Mean",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel2_mean", "HitResiduals_TEC_PLUS_wheel2_mean"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel2_rms_group",
			plot_title: "HitResiduals TEC Wheel 2 RMS",
			y_title: "HitResiduals TEC Wheel 2 RMS",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel2_rms", "HitResiduals_TEC_PLUS_wheel2_rms"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel3_mean_group",
			plot_title: "HitResiduals TEC Wheel 3 Mean",
			y_title: "HitResiduals TEC Wheel 3 Mean",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel3_mean", "HitResiduals_TEC_PLUS_wheel3_mean"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel3_rms_group",
			plot_title: "HitResiduals TEC Wheel 3 RMS",
			y_title: "HitResiduals TEC Wheel 3 RMS",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel3_rms", "HitResiduals_TEC_PLUS_wheel3_rms"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel4_mean_group",
			plot_title: "HitResiduals TEC Wheel 4 Mean",
			y_title: "HitResiduals TEC Wheel 4 Mean",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel4_mean", "HitResiduals_TEC_PLUS_wheel4_mean"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel4_rms_group",
			plot_title: "HitResiduals TEC Wheel 4 RMS",
			y_title: "HitResiduals TEC Wheel 4 RMS",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel4_rms", "HitResiduals_TEC_PLUS_wheel4_rms"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel5_mean_group",
			plot_title: "HitResiduals TEC Wheel 5 Mean",
			y_title: "HitResiduals TEC Wheel 5 Mean",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel5_mean", "HitResiduals_TEC_PLUS_wheel5_mean"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel5_rms_group",
			plot_title: "HitResiduals TEC Wheel 5 RMS",
			y_title: "HitResiduals TEC Wheel 5 RMS",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel5_rms", "HitResiduals_TEC_PLUS_wheel5_rms"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel6_mean_group",
			plot_title: "HitResiduals TEC Wheel 6 Mean",
			y_title: "HitResiduals TEC Wheel 6 Mean",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel6_mean", "HitResiduals_TEC_PLUS_wheel6_mean"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel6_rms_group",
			plot_title: "HitResiduals TEC Wheel 6 RMS",
			y_title: "HitResiduals TEC Wheel 6 RMS",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel6_rms", "HitResiduals_TEC_PLUS_wheel6_rms"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel7_mean_group",
			plot_title: "HitResiduals TEC Wheel 7 Mean",
			y_title: "HitResiduals TEC Wheel 7 Mean",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel7_mean", "HitResiduals_TEC_PLUS_wheel7_mean"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel7_rms_group",
			plot_title: "HitResiduals TEC Wheel 7 RMS",
			y_title: "HitResiduals TEC Wheel 7 RMS",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel7_rms", "HitResiduals_TEC_PLUS_wheel7_rms"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel8_mean_group",
			plot_title: "HitResiduals TEC Wheel 8 Mean",
			y_title: "HitResiduals TEC Wheel 8 Mean",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel8_mean", "HitResiduals_TEC_PLUS_wheel8_mean"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel8_rms_group",
			plot_title: "HitResiduals TEC Wheel 8 RMS",
			y_title: "HitResiduals TEC Wheel 8 RMS",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel8_rms", "HitResiduals_TEC_PLUS_wheel8_rms"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel9_mean_group",
			plot_title: "HitResiduals TEC Wheel 9 Mean",
			y_title: "HitResiduals TEC Wheel 9 Mean",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel9_mean", "HitResiduals_TEC_PLUS_wheel9_mean"],
		},
		{
			name: "HitResiduals_TEC_MINUS_wheel9_rms_group",
			plot_title: "HitResiduals TEC Wheel 9 RMS",
			y_title: "HitResiduals TEC Wheel 9 RMS",
			subsystem: "SiStrips",
			correlation: false,
			series: ["HitResiduals_TEC_MINUS_wheel9_rms", "HitResiduals_TEC_PLUS_wheel9_rms"],
		},
		{
			name: "NClust_ONTk_TEC_MINUS_mean_group",
			plot_title: "Avg. N_{Clusters} (ON-Track)",
			y_title: "Avg. N_{Clusters} (ON-Track)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["NClust_ONTk_TEC_MINUS_mean", "NClust_ONTk_TEC_PLUS_mean"],
		},
		{
			name: "NClust_ONTk_TEC_MINUS_count_group",
			plot_title: "N_{Clusters} (ON-Track)",
			y_title: "N_{Clusters} (ON-Track)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["NClust_ONTk_TEC_MINUS_count", "NClust_ONTk_TEC_PLUS_count"],
		},
		{
			name: "NClust_OFFTk_TEC_MINUS_mean_group",
			plot_title: "Avg. N_{Clusters} (OFF-Track)",
			y_title: "Avg. N_{Clusters} (OFF-Track)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["NClust_OFFTk_TEC_MINUS_mean", "NClust_OFFTk_TEC_PLUS_mean"],
		},
		{
			name: "NClust_OFFTk_TEC_MINUS_count_group",
			plot_title: "N_{Clusters} (OFF-Track)",
			y_title: "N_{Clusters} (OFF-Track)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["NClust_OFFTk_TEC_MINUS_count", "NClust_OFFTk_TEC_PLUS_count"],
		},
		{
			name: "NClust_ONTk_TID_MINUS_mean_group",
			plot_title: "Avg. N_{Clusters} (ON-Track)",
			y_title: "Avg. N_{Clusters} (ON-Track)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["NClust_ONTk_TID_MINUS_mean", "NClust_ONTk_TID_PLUS_mean"],
		},
		{
			name: "NClust_ONTk_TID_MINUS_count_group",
			plot_title: "N_{Clusters} (ON-Track)",
			y_title: "N_{Clusters} (ON-Track)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["NClust_ONTk_TID_MINUS_count", "NClust_ONTk_TID_PLUS_count"],
		},
		{
			name: "NClust_OFFTk_TID_MINUS_mean_group",
			plot_title: "Avg. N_{Clusters} (OFF-Track)",
			y_title: "Avg. N_{Clusters} (OFF-Track)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["NClust_OFFTk_TID_MINUS_mean", "NClust_OFFTk_TID_PLUS_mean"],
		},
		{
			name: "NClust_OFFTk_TID_MINUS_count_group",
			plot_title: "N_{Clusters} (OFF-Track)",
			y_title: "N_{Clusters} (OFF-Track)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["NClust_OFFTk_TID_MINUS_count", "NClust_OFFTk_TID_PLUS_count"],
		},
		{
			name: "clusterStoN_ONTk_TOB_L1_mpv_group",
			plot_title: "S/N (mpv)",
			y_title: "S/N (mpv)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TOB_L1_mpv", "clusterStoN_ONTk_TOB_L2_mpv", "clusterStoN_ONTk_TOB_L3_mpv", "clusterStoN_ONTk_TOB_L4_mpv", "clusterStoN_ONTk_TOB_L5_mpv", "clusterStoN_ONTk_TOB_L6_mpv"],
		},
		{
			name: "clusterStoN_ONTk_TID_MINUS_mpv_group",
			plot_title: "S/N (mpv)",
			y_title: "S/N (mpv)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TID_MINUS_mpv", "clusterStoN_ONTk_TID_PLUS_mpv"],
		},
		{
			name: "clusterStoN_ONTk_TEC_MINUS_mpv_group",
			plot_title: "S/N (mpv)",
			y_title: "S/N (mpv)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TEC_MINUS_mpv", "clusterStoN_ONTk_TEC_PLUS_mpv"],
		},
		{
			name: "clusterStoN_ONTk_TID_PLUS_R1_mpv_group",
			plot_title: "S/N (mpv)",
			y_title: "S/N (mpv)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TID_PLUS_R1_mpv", "clusterStoN_ONTk_TID_PLUS_R2_mpv", "clusterStoN_ONTk_TID_PLUS_R3_mpv", "clusterStoN_ONTk_TID_PLUS_W1_mpv", "clusterStoN_ONTk_TID_PLUS_W2_mpv", "clusterStoN_ONTk_TID_PLUS_W3_mpv"],
		},
		{
			name: "clusterStoN_ONTk_TEC_PLUS_R1_mpv_group",
			plot_title: "S/N (mpv)",
			y_title: "S/N (mpv)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TEC_PLUS_R1_mpv", "clusterStoN_ONTk_TEC_PLUS_R2_mpv", "clusterStoN_ONTk_TEC_PLUS_R3_mpv", "clusterStoN_ONTk_TEC_PLUS_R4_mpv", "clusterStoN_ONTk_TEC_PLUS_R5_mpv", "clusterStoN_ONTk_TEC_PLUS_R6_mpv", "clusterStoN_ONTk_TEC_PLUS_R7_mpv"],
		},
		{
			name: "clusterStoN_ONTk_TEC_PLUS_W1_mpv_group",
			plot_title: "S/N (mpv)",
			y_title: "S/N (mpv)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TEC_PLUS_W1_mpv", "clusterStoN_ONTk_TEC_PLUS_W2_mpv", "clusterStoN_ONTk_TEC_PLUS_W3_mpv", "clusterStoN_ONTk_TEC_PLUS_W4_mpv", "clusterStoN_ONTk_TEC_PLUS_W5_mpv", "clusterStoN_ONTk_TEC_PLUS_W6_mpv", "clusterStoN_ONTk_TEC_PLUS_W7_mpv", "clusterStoN_ONTk_TEC_PLUS_W8_mpv", "clusterStoN_ONTk_TEC_PLUS_W9_mpv"],
		},
		{
			name: "TotalNumberOfCluster__TID__MINUS_group",
			plot_title: "Average N_{Clusters}",
			y_title: "Average N_{Clusters}",
			subsystem: "SiStrips",
			correlation: false,
			series: ["TotalNumberOfCluster__TID__MINUS", "TotalNumberOfCluster__TID__PLUS"],
		},
		{
			name: "TotalNumberOfCluster__TEC__MINUS_group",
			plot_title: "Average N_{Clusters}",
			y_title: "Average N_{Clusters}",
			subsystem: "SiStrips",
			correlation: false,
			series: ["TotalNumberOfCluster__TEC__MINUS", "TotalNumberOfCluster__TEC__PLUS"],
		},
		{
			name: "clusterStoN_ONTk_TID_MINUS_R1_mpv_group",
			plot_title: "S/N (mpv)",
			y_title: "S/N (mpv)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TID_MINUS_R1_mpv", "clusterStoN_ONTk_TID_MINUS_R2_mpv", "clusterStoN_ONTk_TID_MINUS_R3_mpv", "clusterStoN_ONTk_TID_MINUS_W1_mpv", "clusterStoN_ONTk_TID_MINUS_W2_mpv", "clusterStoN_ONTk_TID_MINUS_W3_mpv"],
		},
		{
			name: "clusterStoN_ONTk_TEC_MINUS_R1_mpv_group",
			plot_title: "S/N (mpv)",
			y_title: "S/N (mpv)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TEC_MINUS_R1_mpv", "clusterStoN_ONTk_TEC_MINUS_R2_mpv", "clusterStoN_ONTk_TEC_MINUS_R3_mpv", "clusterStoN_ONTk_TEC_MINUS_R4_mpv", "clusterStoN_ONTk_TEC_MINUS_R5_mpv", "clusterStoN_ONTk_TEC_MINUS_R6_mpv", "clusterStoN_ONTk_TEC_MINUS_R7_mpv"],
		},
		{
			name: "clusterStoN_ONTk_TEC_MINUS_W1_mpv_group",
			plot_title: "S/N (mpv)",
			y_title: "S/N (mpv)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TEC_MINUS_W1_mpv", "clusterStoN_ONTk_TEC_MINUS_W2_mpv", "clusterStoN_ONTk_TEC_MINUS_W3_mpv", "clusterStoN_ONTk_TEC_MINUS_W4_mpv", "clusterStoN_ONTk_TEC_MINUS_W5_mpv", "clusterStoN_ONTk_TEC_MINUS_W6_mpv", "clusterStoN_ONTk_TEC_MINUS_W7_mpv", "clusterStoN_ONTk_TEC_MINUS_W8_mpv", "clusterStoN_ONTk_TEC_MINUS_W9_mpv"],
		},
		{
			name: "clusterStoN_ONTk_TID_MINUS_mean_group",
			plot_title: "S/N (mean)",
			y_title: "S/N (mean)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TID_MINUS_mean", "clusterStoN_ONTk_TID_PLUS_mean"],
		},
		{
			name: "clusterStoN_ONTk_TID_PLUS_mean_group",
			plot_title: "S/N (mean)",
			y_title: "S/N (mean)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TID_PLUS_mean", "clusterStoN_ONTk_TID_MINUS_mean"],
		},
		{
			name: "clusterStoN_ONTk_TEC_MINUS_mean_group",
			plot_title: "S/N (mean)",
			y_title: "S/N (mean)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TEC_MINUS_mean", "clusterStoN_ONTk_TEC_PLUS_mean"],
		},
		{
			name: "clusterStoN_ONTk_TEC_PLUS_mean_group",
			plot_title: "S/N (mean)",
			y_title: "S/N (mean)",
			subsystem: "SiStrips",
			correlation: false,
			series: ["clusterStoN_ONTk_TEC_PLUS_mean", "clusterStoN_ONTk_TEC_MINUS_mean"],
		},

		// =========================================== Muons ===========================================

		{
			name: "Mean_of_BX_Barrel_Wheels",
			plot_title: "Mean of BX distribution (barrel)",
			y_title: "Mean of BX distribution",
			subsystem: "RPC",
			correlation: false,
			series: ["BX_w0", "BX_wp1", "BX_wp2", "BX_wm1", "BX_wm2"],
		},
		{
			name: "Mean_of_BX_Endcap_pDisks",
			plot_title: "Mean of BX distribution (endcap +)",
			y_title: "Mean of BX distribution",
			subsystem: "RPC",
			correlation: false,
			series: ["BX_dp1", "BX_dp2", "BX_dp3", "BX_dp4"],
		},
		{
			name: "Mean_of_BX_Encap_mDisks",
			plot_title: "Mean of BX distribution (endcap -)",
			y_title: "Mean of BX distribution",
			subsystem: "RPC",
			correlation: false,
			series: ["BX_dm1", "BX_dm2", "BX_dm3", "BX_dm4"],
		},
		{
			name: "Avg_of_Cluster_Size",
			plot_title: "Average of cluster size distribution",
			y_title: "Average cluster size",
			subsystem: "RPC",
			correlation: false,
			series: ["ClusterSize_barrel", "ClusterSize_endcap-", "ClusterSize_endcap+"],
		},
		{
			name: "Mean_Of_Residuals",
			plot_title: "Mean of segment - hit residuals",
			y_title: "Mean of residuals distributions (both phi and theta superlayers)",
			subsystem: "DT",
			correlation: false,
			series: ["MeanRes_Phi", "MeanRes_Theta_YB0", "MeanRes_Theta_YB1", "MeanRes_Theta_YB2"],
		},
		{
			name: "Sigma_Of_Residuals",
			plot_title: "Sigma of segment - hit residuals",
			y_title: "Sigma of residuals distributions (both phi and theta superlayers)",
			subsystem: "DT",
			correlation: false,
			series: ["SigmaRes_Phi", "SigmaRes_Theta_YB0", "SigmaRes_Theta_YB1", "SigmaRes_Theta_YB2"],
		},
		{
			name: "Mean_Of_t0_in_MB1",
			plot_title: "Mean of segment t0 distribution (MB1)",
			y_title: "Mean of t0 distribution (MB1)",
			subsystem: "DT",
			correlation: false,
			series: ["MeanT0_MB1_YB-2", "MeanT0_MB1_YB-1", "MeanT0_MB1_YB0", "MeanT0_MB1_YB1", "MeanT0_MB1_YB2"],
		},
		{
			name: "Mean_Of_t0_MB2",
			plot_title: "Mean of segment t0 distribution (MB2)",
			y_title: "Mean of t0 distribution (MB2)",
			subsystem: "DT",
			correlation: false,
			series: ["MeanT0_MB2_YB-2", "MeanT0_MB2_YB-1", "MeanT0_MB2_YB0", "MeanT0_MB2_YB1", "MeanT0_MB2_YB2"],
		},
		{
			name: "Mean_Of_t0_MB3",
			plot_title: "Mean of segment t0 distribution (MB3)",
			y_title: "Mean of t0 distribution (MB3)",
			subsystem: "DT",
			correlation: false,
			series: ["MeanT0_MB3_YB-2", "MeanT0_MB3_YB-1", "MeanT0_MB3_YB0", "MeanT0_MB3_YB1", "MeanT0_MB3_YB2"],
		},
		{
			name: "Mean_Of_t0_MB4",
			plot_title: "Mean of segment t0 distribution (MB4)",
			y_title: "Mean of t0 distribution (MB4)",
			subsystem: "DT",
			correlation: false,
			series: ["MeanT0_MB4_YB-2", "MeanT0_MB4_YB-1", "MeanT0_MB4_YB0", "MeanT0_MB4_YB1", "MeanT0_MB4_YB2"],
		},
		{
			name: "Residual_Width",
			plot_title: "Residual Width",
			y_title: "Width of segment - hit residual",
			subsystem: "CSC",
			correlation: false,
			series: ["Residual_Width_me-11a", "Residual_Width_me-11b", "Residual_Width_me-12", "Residual_Width_me-13", "Residual_Width_me-21", "Residual_Width_me-22", "Residual_Width_me-31", "Residual_Width_me-32", "Residual_Width_me-41", "Residual_Width_me-42", "Residual_Width_me+11a", "Residual_Width_me+11b", "Residual_Width_me+12", "Residual_Width_me+13", "Residual_Width_me+21", "Residual_Width_me+22", "Residual_Width_me+31", "Residual_Width_me+32", "Residual_Width_me+41", "Residual_Width_me+42"],
		},
		{
			name: "PedestalNoise_Width",
			plot_title: "Pedestal Noise Width",
			y_title: "Width of pedestal noise",
			subsystem: "CSC",
			correlation: false,
			series: ["PedestalNoise_Width_me-11a", "PedestalNoise_Width_me-11b", "PedestalNoise_Width_me-12", "PedestalNoise_Width_me-13", "PedestalNoise_Width_me-21", "PedestalNoise_Width_me-22", "PedestalNoise_Width_me-31", "PedestalNoise_Width_me-32", "PedestalNoise_Width_me-41", "PedestalNoise_Width_me-42", "PedestalNoise_Width_me+11a", "PedestalNoise_Width_me+11b", "PedestalNoise_Width_me+12", "PedestalNoise_Width_me+13", "PedestalNoise_Width_me+21", "PedestalNoise_Width_me+22", "PedestalNoise_Width_me+31", "PedestalNoise_Width_me+32", "PedestalNoise_Width_me+41", "PedestalNoise_Width_me+42"],
		},

    ]
    
    return {
        displayGroups: displayGroups
    }
}())
